#!/usr/bin/env node
/**
 * Schema drift — committed expected schema ↔ clean scratch replay.
 *
 * Normal mode compares expected-schema.json with the manifest produced by a
 * clean replay of the current migrations. Snapshot mode intentionally skips
 * the old expected-schema comparison: the runner first proves migration
 * immutability/replay/security, then replaces expected-schema.json only if no
 * blocking findings exist.
 *
 * This check is scratch-only. It does not connect to or mutate a live Supabase
 * project.
 */
import { join } from "node:path";
import { readJson, CONTRACT_DIR } from "../../lib/common.mjs";
import { extractManifest, normalizeForComparison } from "../../lib/manifest.mjs";

export const id = "G-SCHEMA-DRIFT";
export const title = "Clean migration replay must match the committed expected schema";
export const category = "schema";
export const defaultSeverity = "HIGH";
export const mode = "dynamic";

export async function run(ctx) {
  const { report, db } = ctx;
  const expectedPath = join(CONTRACT_DIR, "expected-schema.json");
  let expected;
  try {
    expected = readJson(expectedPath);
  } catch {
    if (ctx.cli.snapshot) {
      report.pass(
        this,
        `${id}-NO-MANIFEST`,
        "expected-schema.json will be generated by this safe snapshot run",
        `${expectedPath} not found (snapshot mode)`,
      );
    } else {
      report.fail(this, {
        severity: "HIGH",
        id: `${id}-NO-MANIFEST`,
        title: "expected-schema.json is missing — run `npm run db:guardian:snapshot`",
        evidence: `${expectedPath} not found`,
      });
    }
    return;
  }

  const actual = normalizeForComparison(await extractManifest(db));

  if (ctx.cli.snapshot) {
    report.pass(
      this,
      `${id}-SNAPSHOT-MODE`,
      "Snapshot mode: old expected schema comparison intentionally skipped",
      `clean replay manifest ready: tables=${Object.keys(actual.tables).length}, views=${Object.keys(actual.views).length}, functions=${Object.keys(actual.functions).length}`,
    );
    return;
  }

  const exp = normalizeForComparison(expected);
  const diffs = [];
  const add = (sev, key, titleText, evidence) =>
    diffs.push({ sev, key, titleText, evidence });

  const driftReasons = [];
  for (const t of Object.keys(actual.tables)) {
    if (!exp.tables[t]) driftReasons.push(`new table ${t} (not in expected-schema.json)`);
  }
  for (const t of Object.keys(exp.tables)) {
    if (!actual.tables[t]) driftReasons.push(`table ${t} missing from replay`);
  }
  if (driftReasons.length > 0) {
    add(
      "HIGH",
      "SNAPSHOT-STALE",
      "Migrations and expected-schema.json disagree — regenerate the snapshot",
      driftReasons.slice(0, 20).join("\n"),
    );
  } else {
    report.pass(
      this,
      `${id}-SNAPSHOT`,
      "Committed expected-schema.json matches the clean replay table set",
      `tables: ${Object.keys(actual.tables).length}`,
    );
  }

  for (const t of Object.keys(exp.tables)) {
    const a = actual.tables[t];
    const e = exp.tables[t];
    if (!a) {
      add(
        "CRITICAL",
        "TABLE-MISSING",
        `Table ${t} missing from actual schema`,
        "expected per canonical contract",
      );
      continue;
    }
    if (a.rls !== e.rls) {
      add(
        "CRITICAL",
        "RLS-DISABLED",
        `RLS state changed on ${t}`,
        `expected rls=${e.rls}, actual=${a.rls}`,
      );
    }
    for (const c of Object.keys(e.columns)) {
      const ac = a.columns[c];
      if (!ac) {
        add(
          "HIGH",
          "COLUMN-MISSING",
          `Column ${t}.${c} missing`,
          `expected ${e.columns[c].type}(${e.columns[c].precision},${e.columns[c].scale})`,
        );
        continue;
      }
      const typeEq =
        ac.type === e.columns[c].type &&
        ac.precision === e.columns[c].precision &&
        ac.scale === e.columns[c].scale;
      if (!typeEq) {
        add(
          "HIGH",
          "COLUMN-TYPE",
          `Column ${t}.${c} type changed`,
          `expected ${e.columns[c].type}(${e.columns[c].precision},${e.columns[c].scale}), actual ${ac.type}(${ac.precision},${ac.scale})`,
        );
      }
    }
    for (const c of Object.keys(a.columns)) {
      if (!e.columns[c]) {
        add(
          "LOW",
          "COLUMN-ADDED",
          `Column ${t}.${c} added outside the contract snapshot`,
          `actual ${a.columns[c].type}(${a.columns[c].precision},${a.columns[c].scale})`,
        );
      }
    }
    for (const fk of e.foreignKeys) {
      const same = a.foreignKeys.some(
        (f) => f.cols.join(",") === fk.cols.join(",") && f.refTable === fk.refTable,
      );
      if (!same) {
        add(
          "HIGH",
          "FK-MISSING",
          `FK on ${t} changed/missing`,
          `${fk.cols.join(",")} → ${fk.refTable}(${fk.refCols.join(",")})`,
        );
      }
    }
    for (const u of e.uniques) {
      const same = a.uniques.some((x) => x.cols.join(",") === u.cols.join(","));
      if (!same) {
        add(
          "HIGH",
          "UNIQUE-MISSING",
          `UNIQUE constraint on ${t} missing/changed`,
          `${u.cols.join(",")}`,
        );
      }
    }
    for (const chk of e.checks) {
      if (!a.checks.includes(chk)) {
        add("HIGH", "CHECK-MISSING", `CHECK constraint ${t}.${chk} missing`, "");
      }
    }
    const missingIdx = e.indexes.filter((i) => !a.indexes.includes(i));
    if (missingIdx.length > 0) {
      add("MEDIUM", "INDEX-MISSING", `Indexes missing on ${t}`, missingIdx.join(", "));
    }
  }

  for (const t of Object.keys(actual.tables)) {
    if (!exp.tables[t]) {
      add("LOW", "TABLE-ADDED", `Table ${t} exists in replay but not in the contract snapshot`, "");
    }
  }

  for (const [name, v] of Object.entries(exp.views)) {
    const av = actual.views[name];
    if (!av) {
      add("HIGH", "VIEW-MISSING", `View ${name} missing from actual schema`, "");
    } else if (av.securityInvoker !== v.securityInvoker) {
      add(
        "HIGH",
        "VIEW-INVOKER",
        `View ${name} security_invoker changed`,
        `expected ${v.securityInvoker}, actual ${av.securityInvoker}`,
      );
    }
  }

  for (const [key, f] of Object.entries(exp.functions)) {
    const af = actual.functions[key];
    if (!af) {
      add("HIGH", "FN-MISSING", `Function ${key} missing from actual schema`, "");
      continue;
    }
    if (af.secdef !== f.secdef) {
      add(
        "HIGH",
        "FN-SECDEF",
        `Function ${key} SECURITY DEFINER flag changed`,
        `expected ${f.secdef}, actual ${af.secdef}`,
      );
    }
    if (af.searchPathPinned !== f.searchPathPinned) {
      add(
        "HIGH",
        "FN-SEARCH-PATH",
        `Function ${key} search_path pinning changed`,
        `expected ${f.searchPathPinned}, actual ${af.searchPathPinned}`,
      );
    }
  }

  if (diffs.length === 0) {
    report.pass(
      this,
      `${id}-CLEAN`,
      "No schema drift: clean replay matches the canonical contract snapshot",
      `tables=${Object.keys(actual.tables).length}, views=${Object.keys(actual.views).length}, functions=${Object.keys(actual.functions).length}`,
    );
    return;
  }

  for (const d of diffs) {
    report.fail(this, {
      severity: d.sev,
      id: `${id}-${d.key}`,
      title: d.titleText,
      evidence: d.evidence.slice(0, 2000),
    });
  }
}
