import { useState, type FormEvent } from "react";
import { useNavigate } from "@tanstack/react-router";
import { CalendarDays, MapPin, Plus } from "lucide-react";
import { useAuth } from "@/app/AuthContext";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Dialog } from "@/components/ui/Dialog";
import { EmptyState } from "@/components/ui/EmptyState";
import { Field } from "@/components/ui/Field";
import { Input } from "@/components/ui/Input";
import { PageHeader } from "@/components/ui/PageHeader";
import { Select } from "@/components/ui/Select";
import { Textarea } from "@/components/ui/Textarea";
import { useCustomers } from "@/features/customers/customers.api";
import { OwnerVoiceButton } from "@/features/ownerVoice/OwnerVoiceButton";
import { buildEventsListVoiceSummary } from "@/features/ownerVoice/screenSummary";
import { arabicError, useCreateEvent, useEvents, type EventStatus } from "./events.api";

const labels:Record<EventStatus,string>={DRAFT:"مسودة",QUOTED:"تم التسعير",CONFIRMED:"مؤكدة",PREPARING:"قيد التجهيز",DISPATCHED:"تم الإرسال",IN_PROGRESS:"جارية",RETURNING:"قيد الإرجاع",CLOSED:"مغلقة",CANCELLED:"ملغاة"};
export function EventsPage(){const {currentOrganization}=useAuth();const orgId=currentOrganization?.id??null;const events=useEvents(orgId);const customers=useCustomers(orgId);const create=useCreateEvent(orgId);const navigate=useNavigate();const [open,setOpen]=useState(false);const [error,setError]=useState("");
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);try{const event=await create.mutateAsync({customerId:String(f.get("customer")),title:String(f.get("title")),eventType:String(f.get("type")),startAt:String(f.get("start")),endAt:String(f.get("end")),guestCount:Number(f.get("guests")),venue:String(f.get("venue")),contactName:String(f.get("contact")??""),contactPhone:String(f.get("phone")??""),notes:String(f.get("notes")??"")});setOpen(false);void navigate({to:"/events/$eventId",params:{eventId:event.id}})}catch(x){setError(arabicError(x))}}
const voiceSummary=events.isSuccess?buildEventsListVoiceSummary({events:events.data}):null;return <><PageHeader title="المناسبات" description="تخطيط المناسبات والتسعير والموارد من مكان واحد" actions={<><OwnerVoiceButton summary={voiceSummary}/><Button onClick={()=>setOpen(true)}><Plus className="h-5 w-5"/> مناسبة جديدة</Button></>}/>{events.isLoading?<p>جارٍ التحميل…</p>:!events.data?.length?<EmptyState title="لا توجد مناسبات" description="أنشئ أول مناسبة لبدء التخطيط." action={<Button onClick={()=>setOpen(true)}>+ مناسبة جديدة</Button>}/>:<div className="grid gap-3 md:grid-cols-2">{events.data.map(ev=><button key={ev.id} onClick={()=>void navigate({to:"/events/$eventId",params:{eventId:ev.id}})} className="text-right"><Card className="h-full transition hover:border-brand-300"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-sm text-slate-500" dir="ltr">{ev.event_number}</p><h2 className="mt-1 text-lg font-bold">{ev.title}</h2></div><Badge tone={ev.status==="CANCELLED"?"danger":"brand"}>{labels[ev.status]}</Badge></div><div className="mt-4 space-y-2 text-sm text-slate-600"><p className="flex gap-2"><CalendarDays className="h-4 w-4"/>{new Date(ev.start_at).toLocaleString("ar-OM",{timeZone:"Asia/Muscat"})}</p><p className="flex gap-2"><MapPin className="h-4 w-4"/>{ev.venue_name}</p><p>{ev.guest_count} ضيف</p></div></Card></button>)}</div>}
<Dialog open={open} onOpenChange={setOpen} title="مناسبة جديدة"><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="العميل"><Select name="customer" required defaultValue=""><option value="" disabled>اختر العميل</option>{customers.data?.filter(c=>c.is_active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Field label="عنوان المناسبة"><Input name="title" required/></Field><Field label="نوع المناسبة"><Input name="type" placeholder="زفاف، مؤتمر…" required/></Field><Field label="عدد الضيوف"><Input name="guests" type="number" min="1" required/></Field><Field label="البداية"><Input name="start" type="datetime-local" required/></Field><Field label="النهاية"><Input name="end" type="datetime-local" required/></Field><Field label="الموقع"><Input name="venue" required/></Field><Field label="اسم جهة الاتصال"><Input name="contact"/></Field><Field label="هاتف التواصل"><Input name="phone" inputMode="tel"/></Field><div className="sm:col-span-2"><Field label="ملاحظات"><Textarea name="notes"/></Field></div>{error&&<p className="sm:col-span-2 text-sm font-bold text-red-700" role="alert">{error}</p>}<div className="sm:col-span-2 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>إلغاء</Button><Button type="submit" disabled={create.isPending}>{create.isPending?"جارٍ الإنشاء…":"إنشاء المناسبة"}</Button></div></form></Dialog></>}
